version: '3'
services: 
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    hostname: prometheus
    volumes:
      - ./conf:/etc/prometheus
    # volumes:
    #   - ./conf:/proconf
    # command: 
    #   - --config.file=/proconf/prometheus.yml
    #   - --storage.tsdb.path=/prometheus
    #   - --web.console.libraries=/usr/share/prometheus/console_libraries
    #   - --web.console.templates=/usr/share/prometheus/consoles
    ports:
      - 9090:9090

  node-exporter:
    image: bitnami/node-exporter:1.3.1
    container_name: node-exporter
    hostname: node-exporter
    depends_on:
      - prometheus
    ports:
      - 9100:9100

  # grafana:
  #   image: grafana/grafana:9.1.5
  #   container_name: grafana
  #   hostname: grafana
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3000:3000


  