version: "3"
services:
  zookeeper:
    hostname: zookeeper
    container_name: nifi-zookeeper
    image: 'bitnami/zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  nifi:
    image: apache/nifi:latest
    volumes: 
      - ./mylib:/opt/nifi/nifi-current/lib/mylib
    ports:
      - "8080:8080" # Unsecured HTTP Web Port
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379