version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  
  broker:
    image: confluentinc/cp-enterprise-kafka:6.0.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  clickhouse1:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse1
    hostname: clickhouse1
    depends_on:
      - zookeeper
      - broker
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./conf/clickhouse1/config.xml:/etc/clickhouse-server/config.xml
      - ./conf/clickhouse1/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/clickhouse1/config.d:/etc/clickhouse-server/config.d
      - ./conf/clickhouse1/users.d:/etc/clickhouse-server/users.d

  clickhouse2:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse2
    hostname: clickhouse2
    depends_on:
      - zookeeper
      - broker
      - clickhouse1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./conf/clickhouse2/config.xml:/etc/clickhouse-server/config.xml
      - ./conf/clickhouse2/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/clickhouse2/config.d:/etc/clickhouse-server/config.d
      - ./conf/clickhouse2/users.d:/etc/clickhouse-server/users.d
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  
  sinker:
    image: quay.io/housepower/clickhouse_sinker:latest
    container_name: sinker
    hostname: sinker
    volumes:
      - ./conf/sinker/clickhouse_sinker.json:/etc/clickhouse_sinker.json
    depends_on:
      - zookeeper
      - broker
      - clickhouse1
      - clickhouse2