version: "2.1"
services:
  jobmanager:
    image: flink:1.11.0
    container_name: jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - STATE_BACKEND=rocksdb
      - STATE_BACKEND_INCREMENTAL=true
      - STATE_CHECKPOINTS_DIR=hdfs://namenode:8020/flink-checkpoints
      - STATE_SAVEPOINTS_DIR=hdfs://namenode:8020/flink-savepoints

  taskmanager1:
    image: flink:1.11.0
    container_name: taskmanager1
    hostname: taskmanager1
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=3
      - STATE_BACKEND=rocksdb
      - STATE_BACKEND_INCREMENTAL=true
      - STATE_CHECKPOINTS_DIR=hdfs://namenode:8020/flink-checkpoints
      - STATE_SAVEPOINTS_DIR=hdfs://namenode:8020/flink-savepoints

  taskmanager2:
    image: flink:1.11.0
    container_name: taskmanager2
    hostname: taskmanager2
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
      - TASK_MANAGER_NUMBER_OF_TASK_SLOTS=3
      - STATE_BACKEND=rocksdb
      - STATE_BACKEND_INCREMENTAL=true
      - STATE_CHECKPOINTS_DIR=hdfs://namenode:8020/flink-checkpoints
      - STATE_SAVEPOINTS_DIR=hdfs://namenode:8020/flink-savepoints

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    hostname: namenode
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    hostname: datanode
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  kafka:
    image: 'bitnami/kafka:2.8.1'
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,EXTERNAL://kafka:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper