version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.5.9
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  clickhouse1:
    image: yandex/clickhouse-server:21.8.14.5
    container_name: clickhouse1
    hostname: clickhouse1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config1.xml:/etc/clickhouse-server/config.xml
      - ./docker-entrypoint-initdb.d1:/docker-entrypoint-initdb.d
    ports:
      - 8123:8123
      - 9000:9000
      - 9004:9004
    depends_on:
      - zookeeper

  clickhouse2:
    image: yandex/clickhouse-server:21.8.14.5
    container_name: clickhouse2
    hostname: clickhouse2
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config2.xml:/etc/clickhouse-server/config.xml
      - ./docker-entrypoint-initdb.d2:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper

  clickhouse3:
    image: yandex/clickhouse-server:21.8.14.5
    container_name: clickhouse3
    hostname: clickhouse3
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config3.xml:/etc/clickhouse-server/config.xml
      - ./docker-entrypoint-initdb.d3:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper

  clickhouse4:
    image: yandex/clickhouse-server:21.8.14.5
    container_name: clickhouse4
    hostname: clickhouse4
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config4.xml:/etc/clickhouse-server/config.xml
      - ./docker-entrypoint-initdb.d4:/docker-entrypoint-initdb.d
    depends_on:
      - zookeeper

  proxy1:
    image: contentsquareplatform/chproxy:1.15.1
    container_name: proxy1
    hostname: proxy1
    volumes:
      - ./proxy-config.yml:/config.yml
    command: ["-config", "/config.yml"]
    ports:
      - 9090:9090
    depends_on:
      - clickhouse1
      - clickhouse2
      - clickhouse3
      - clickhouse4
  
  proxy2:
    image: contentsquareplatform/chproxy:1.15.1
    container_name: proxy2
    hostname: proxy2
    volumes:
      - ./proxy-config.yml:/config.yml
    command: ["-config", "/config.yml"]
    ports:
      - 9091:9090
    depends_on:
      - clickhouse1
      - clickhouse2
      - clickhouse3
      - clickhouse4

    