version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.5.9
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  broker:
    image: bitnami/kafka:2.8.1
    container_name: broker
    hostname: broker
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,EXTERNAL://broker:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  redis:
    image: redis
    container_name: redis
    hostname: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379

  clickhouse1:
    image: clickhouse/clickhouse-server:22.7.2.15
    container_name: clickhouse1
    hostname: clickhouse1
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config1.xml:/etc/clickhouse-server/config.xml
    ports:
      - 8121:8123
      - 9001:9000
    depends_on:
      - zookeeper

  clickhouse2:
    image: clickhouse/clickhouse-server:22.7.2.15
    container_name: clickhouse2
    hostname: clickhouse2
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config2.xml:/etc/clickhouse-server/config.xml
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 8122:8123
      - 9002:9000
    depends_on:
      - zookeeper
      - clickhouse1

  master:
    image: bitnami/spark:3.1.3
    container_name: master
    user: root
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - 4040:4040
      - 8080:8080
      - 7077:7077
    volumes:
      - ./../target/study-spark-1.0-SNAPSHOT.jar:/spark_src/study-spark-1.0-SNAPSHOT.jar
      - ./commit.sh:/commit.sh
      - ./log4j.properties:/opt/bitnami/spark/conf/log4j.properties
  worker1:
    image: bitnami/spark:3.1.3
    container_name: worker1
    user: root
    ports:
      - 8081:8081
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  worker2:
    image: bitnami/spark:3.1.3
    container_name: worker2
    user: root
    ports:
      - 8082:8081
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no