version: '3'
services:

  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.1
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  clickhouse:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse
    hostname: clickhouse
    depends_on:
      - zookeeper
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./conf/config.xml:/etc/clickhouse-server/config.xml
      - ./conf/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/config.d:/etc/clickhouse-server/config.d
      - ./conf/users.d:/etc/clickhouse-server/users.d
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d