version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.5.9
    hostname: zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  clickhouse:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse
    hostname: clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config.xml:/etc/clickhouse-server/config.xml
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 8123:8123
      - 9000:9000
      - 9004:9004

  # bytebase:
  #   image: bytebase/bytebase:0.12.0
  #   container_name: bytebase
  #   hostname: bytebase
  #   command: --data /var/opt/bytebase --host http://localhost --port 8080
  #   volumes:
  #     - ./data:/var/opt/bytebase
  #   ports:
  #     - 8080:8080