version: '3'
services: 
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 300M
        reservations:
          memory: 150M

  broker:
    image: 'bitnami/kafka:2.8.1'
    container_name: broker
    hostname: broker
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://localhost:9092,EXTERNAL://broker:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1000M
        reservations:
          memory: 500M

  manager:
    image: sheepkiller/kafka-manager:latest
    container_name: manager
    hostname: manager
    environment:
      - ZK_HOSTS=zookeeper:2181
    depends_on:
      - zookeeper
    ports:
      - 8900:9000

  # master:
  #   image: bitnami/spark:3.2.2
  #   container_name: master
  #   user: root
  #   environment:
  #     - HADOOP_USER_NAME=hdfsuser
  #     - SPARK_MODE=master
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #   ports:
  #     - 4040:4040
  #     - 8080:8080
  #     - 8282:8282
  #     - 7077:7077
  #   volumes:
  #     - /Users/huangsw/code/funny/funnydb/spark-block-aggregator/quickly-start/log4j.properties:/opt/bitnami/spark/conf/log4j.properties
  #     - ./util:/util
  #     - /Users/huangsw/code/funny/funnydb/spark-block-aggregator/target:/spark_src
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.8'
  #         memory: 1400M
  #       reservations:
  #         memory: 500M
      
  # worker:
  #   image: bitnami/spark:3.2.2
  #   container_name: worker
  #   user: root
  #   depends_on:
  #     - master
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - HADOOP_USER_NAME=hdfsuser
  #     - SPARK_MODE=worker
  #     - SPARK_MASTER_URL=spark://master:7077
  #     - SPARK_WORKER_MEMORY=2500m
  #     - SPARK_WORKER_CORES=2
  #     - SPARK_RPC_AUTHENTICATION_ENABLED=no
  #     - SPARK_RPC_ENCRYPTION_ENABLED=no
  #     - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
  #     - SPARK_SSL_ENABLED=no
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1.2'
  #         memory: 2500M
  #       reservations:
  #         memory: 500M
  
  # namenode:
  #   image: singularities/hadoop:2.8
  #   command: start-hadoop namenode
  #   hostname: namenode
  #   container_name: namenode
  #   environment:
  #     HDFS_USER: hdfsuser
  #   ports:
  #     - "8020:8020"
  #     - "9000:9000"
  #     - "50070:50070"
  #     - "50075:50075"
  #   depends_on:
  #     - zookeeper
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.25'
  #         memory: 1000M
  #       reservations:
  #         memory: 500M

  # clickhouse1:
  #   image: clickhouse/clickhouse-server:22.7.2.15
  #   container_name: clickhouse1
  #   hostname: clickhouse1
  #   ulimits:
  #     nofile:
  #       soft: 262144
  #       hard: 262144
  #     nproc:
  #       soft: 131072
  #       hard: 131072
  #   volumes:
  #     - /Users/huangsw/code/study/study-spark/quickly-start/config1.xml:/etc/clickhouse-server/config.xml
  #   ports:
  #     - 8121:8123
  #     - 9001:9000
  #   depends_on:
  #     - zookeeper
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 800M
  #       reservations:
  #         memory: 300M

  # clickhouse2:
  #   image: clickhouse/clickhouse-server:22.7.2.15
  #   container_name: clickhouse2
  #   hostname: clickhouse2
  #   ulimits:
  #     nofile:
  #       soft: 262144
  #       hard: 262144
  #     nproc:
  #       soft: 131072
  #       hard: 131072
  #   volumes:
  #     - /Users/huangsw/code/study/study-spark/quickly-start/config2.xml:/etc/clickhouse-server/config.xml
  #     - /Users/huangsw/code/study/study-spark/quickly-start/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  #   ports:
  #     - 8122:8123
  #     - 9002:9000
  #   depends_on:
  #     - zookeeper
  #     - clickhouse1
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 800M
  #       reservations:
  #         memory: 300M


  