apiVersion: v1
kind: Pod
metadata:
  name: cm-demo-pod
  namespace: demo # 要和引用的 ConfigMap 在同一个命名空间下
spec:
  containers:
    - name: demo
      image: busybox:1.28
      command:
        - "bin/sh"
        - "-c"
        - "cat /etc/game/game.properties"
      volumeMounts:
      - name: full-config # 这里是下面定义的 volume 名字
        mountPath: /config
        readOnly: true
      - name: part-config
        mountPath: /etc/game/
        readOnly: true
  volumes: # 您可以在 Pod 级别设置卷，然后将其挂载到 Pod 内的容器中
    - name: full-config # 这是 volume 的名字
      configMap:
        name: cm-demo-mix # 提供你想要挂载的 ConfigMap 的名字
    - name: part-config
      configMap:
        name: cm-demo-mix
        items: # 我们也可以只挂载部分的配置
        - key: game.properties
          path: properties