version: "3"
services:
  # prestodb supports hudi table
  # presto:
  #   image: dpp/presto
  #   volumes:
  #     - presto:/var/lib/presto
  #     - presto-logs:/var/lib/presto/var/log
  #     - ./config/presto:/opt/presto/etc:ro
  #     - ./config/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
  #     - ./config/alluxio/alluxio-site.properties:/opt/alluxio/conf/alluxio-site.properties:ro
  #   command: /opt/presto/bin/launcher run
  #   mem_limit: 4g
  #   ports:
  #     - 127.0.0.1:8080:8080

  # another presto, that supports iceberg table
  trino:
    image: dpp/trino
    volumes:
      - presto:/var/lib/trino
      - presto-logs:/var/lib/trino/var/log
      - ./config/trino:/opt/trino/etc:ro
      - ./config/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./config/alluxio/alluxio-site.properties:/opt/alluxio/conf/alluxio-site.properties:ro
    command: /opt/trino/bin/launcher run
    mem_limit: 4g
    ports:
      - 127.0.0.1:8081:8080

  spark:
    image: dpp/spark
    volumes:
      - spark:/root
      - hive-logs:/var/log/hive
      - ./config/spark/hive-site.xml:/opt/spark/conf/hive-site.xml:ro
      - ./config/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./config/spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./config/alluxio/alluxio-site.properties:/opt/alluxio/conf/alluxio-site.properties:ro
    command:
      - sh
      - -xeuc
      - trap 'exit 0' EXIT; sleep inf & wait
    working_dir: /root
    stop_signal: int
    tty: true
    mem_limit: 2g

  hive-metastore:
    image: dpp/hive
    volumes:
      - hive-logs:/var/log/hive
      - ./config/hive/hive-site.xml:/opt/hive/conf/hive-site.xml:ro
      - ./config/hadoop/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml:ro
      - ./config/alluxio/alluxio-site.properties:/opt/alluxio/conf/alluxio-site.properties:ro
    command:
      - bash
      - -xeuc
      - |
        schematool -dbType mysql -initSchema || schematool -dbType mysql -upgradeSchema
        hive --service metastore
    mem_limit: 512m
    environment:
      - HADOOP_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=45.0
    depends_on:
      - hive-db

  hive-db:
    image: "mysql:5.7"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=hive
      - MYSQL_USER=hive
      - MYSQL_PASSWORD=secret
    volumes:
      - "hive-db:/var/lib/mysql"
    mem_limit: 512m

  alluxio-master:
    image: dpp/alluxio
    hostname: alluxio-master
    volumes:
      - alluxio-journal:/opt/alluxio/journal
      - alluxio-ufs:/opt/alluxio/underFSStorage/
      - ./config/alluxio/alluxio-site.properties:/opt/alluxio/conf/alluxio-site.properties
    user: root
    entrypoint: [bash, -xeuc]
    environment:
      - ALLUXIO_JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=45.0
    command:
      - |
        JOURNAL_FOLDER=$$(alluxio getConf alluxio.master.journal.folder)
        if [ ! -d "$$JOURNAL_FOLDER" ]; then
          alluxio formatJournal
        fi
        exec /entrypoint.sh master --no-format
    mem_limit: 1g
    ports:
      - 127.0.0.1:19999:19999

  alluxio-worker:
    image: dpp/alluxio
    hostname: alluxio-worker
    volumes:
      - alluxio-ufs:/opt/alluxio/underFSStorage/
      - alluxio-worker-data:/alluxio-worker-data
      - ./config/alluxio/alluxio-site.properties:/opt/alluxio/conf/alluxio-site.properties
    user: root
    command: worker --no-format
    environment:
      - ALLUXIO_JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=45.0
      - ALLUXIO_WORKER_TIEREDSTORE_LEVEL0_DIRS_PATH=/alluxio-worker-data
    mem_limit: 512m
    depends_on:
      - alluxio-master

  alluxio-proxy:
    image: dpp/alluxio
    hostname: alluxio-proxy
    volumes:
      - ./config/alluxio/alluxio-site.properties:/opt/alluxio/conf/alluxio-site.properties
    user: root
    command: proxy
    environment:
      - ALLUXIO_JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
    mem_limit: 256m
    ports:
      - 127.0.0.1:39999:39999
    depends_on:
      - alluxio-master

  # kafka:
  #   image: dpp/kafka
  #   volumes:
  #     - kafka-data:/bitnami/kafka
  #   environment:
  #     - ALLOW_PLAINTEXT_LISTENER=yes
  #     - KAFKA_ZOOKEEPER_CONNECT=kafka-zookeeper:2181
  #     - KAFKA_HEAP_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
  #     - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
  #     - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
  #     - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://127.0.0.1:9093
  #     - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
  #   ports:
  #     - 127.0.0.1:9093:9093
  #   depends_on:
  #     - kafka-zookeeper
  #   mem_limit: 256m

  # kafka-zookeeper:
  #   image: dpp/zookeeper
  #   volumes:
  #     - kafka-zookeeper-data:/data
  #     - kafka-zookeeper-datalog:/datalog
  #   environment:
  #     - JVMFLAGS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0
  #   mem_limit: 256m

volumes:
  presto:
  presto-logs:
  trino:
  trino-logs:
  spark:
  hive-db:
  hive-logs:
  alluxio-worker-data:
  alluxio-ufs:
  alluxio-journal:
  kafka-data:
  kafka-zookeeper-data:
  kafka-zookeeper-datalog:
