version: '3'
services:

  zookeeper:
    image: bitnami/zookeeper:3.5.9
    hostname: zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  clickhouse1:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse1
    hostname: clickhouse1
    depends_on:
      - zookeeper
      - clickhouse2
    ports:
      - 8121:8123
      - 9001:9004
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./conf/node1/config.xml:/etc/clickhouse-server/config.xml
      - ./conf/node1/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/node1/config.d:/etc/clickhouse-server/config.d
      - ./conf/node1/users.d:/etc/clickhouse-server/users.d
      - ./conf/node1/copier:/etc/clickhouse-server/copier
      - ./conf/node1/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  clickhouse2:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse2
    hostname: clickhouse2
    depends_on:
      - zookeeper
    ports:
      - 8122:8123
      - 9002:9004
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./conf/node2/config.xml:/etc/clickhouse-server/config.xml
      - ./conf/node2/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/node2/config.d:/etc/clickhouse-server/config.d
      - ./conf/node2/users.d:/etc/clickhouse-server/users.d
      - ./conf/node2/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  clickhouse3:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse3
    hostname: clickhouse3
    depends_on:
      - zookeeper
      - clickhouse4
    ports:
      - 8123:8123
      - 9003:9004
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./conf/node3/config.xml:/etc/clickhouse-server/config.xml
      - ./conf/node3/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/node3/config.d:/etc/clickhouse-server/config.d
      - ./conf/node3/users.d:/etc/clickhouse-server/users.d
      - ./conf/node3/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  clickhouse4:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse4
    hostname: clickhouse4
    depends_on:
      - zookeeper
    ports:
      - 8124:8123
      - 9004:9004
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./conf/node4/config.xml:/etc/clickhouse-server/config.xml
      - ./conf/node4/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/node4/config.d:/etc/clickhouse-server/config.d
      - ./conf/node4/users.d:/etc/clickhouse-server/users.d
      - ./conf/node4/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d