apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: demo
type: Opaque
data: # 由于转出时会自动使用 base64 解码，因此这里的值都是 base64 加密后的
  password: UyFCXCpkJHpEc2I9
  username: ZGV2dXNlcg==
stringData: # 也可以使用stringData，这样可以避免自己事先手动用 base64 进行加密
  password: devuser
  username: S!B\*d$zDsb=