version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    container_name: elasticsearch
    privileged: true
    environment:
      - discovery.type=single-node
      - network.publish_host=172.16.12.23
      - indices.fielddata.cache.size=60%
      - xpack.monitoring.collection.enabled=false
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    hostname: elasticsearch
    restart: always
    logging: 
      driver: "json-file"
      options: 
        max-size: "500m"
    networks:
      - esnet
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.2
    container_name: kibana
    privileged: true
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    hostname: kibana
    depends_on:
      - elasticsearch
    volumes:
      - ./kibana/conf/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ./kibana/plugins:/usr/share/kibana/plugins
    restart: always
    logging: 
      driver: "json-file"
      options: 
        max-size: "500m"
    networks:
      - esnet
    ports:
      - "5601:5601"

  # filebeat:
  #   image: docker.elastic.co/beats/filebeat:7.10.2
  #   container_name: filebeat
  #   logging: 
  #     driver: "json-file"
  #     options: 
  #       max-size: "500m"
  #   volumes:
  #     - ./filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
  #     - ./filebeat/data:/usr/share/filebeat/data
  #   networks:
  #     - esnet
  #   depends_on:
  #     - "elasticsearch"
  #     - "kibana"
  
  logstash:
    image: docker.elastic.co/logstash/logstash:7.10.2
    container_name: logstash
    logging: 
      driver: "json-file"
      options: 
        max-size: "500m"
    environment: 
      - LOG_LEVEL=info
    volumes:
      - ./logstash/conf:/usr/share/logstash/pipeline
      - ./logstash/data:/usr/share/logstash/data
    networks:
      - esnet
    depends_on:
      - "elasticsearch"
      - "kibana"

  eshead:
    image: containerize/elastichd:latest
    container_name: eshead
    logging: 
      driver: "json-file"
      options: 
        max-size: "500m"
    networks:
      - esnet
    ports:
      - 9800:9800
    depends_on:
      - "elasticsearch"

networks:
  esnet:
    driver: bridge
