version: '3'
services:

  zookeeper:
    image: bitnami/zookeeper:3.5.9
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  
  clickhouse1:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse1
    hostname: clickhouse1
    deploy:
      resources:
         limits:
            cpus: "2.00"
    depends_on:
      - zookeeper
      - clickhouse2
    ports:
      - 8123:8123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./conf/node1/config.xml:/etc/clickhouse-server/config.xml
      - ./conf/node1/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/node1/config.d:/etc/clickhouse-server/config.d
      - ./conf/node1/users.d:/etc/clickhouse-server/users.d
      - ./conf/node1/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./conf/node1/sql:/sql

  clickhouse2:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse2
    hostname: clickhouse2
    deploy:
      resources:
         limits:
            cpus: "2.00"
    depends_on:
      - zookeeper
    ports:
      - 8124:8123
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./conf/node2/config.xml:/etc/clickhouse-server/config.xml
      - ./conf/node2/users.xml:/etc/clickhouse-server/users.xml
      - ./conf/node2/config.d:/etc/clickhouse-server/config.d
      - ./conf/node2/users.d:/etc/clickhouse-server/users.d
      - ./conf/node2/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
