version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.5.9
    hostname: zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181
    
  clickhouse1:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse1
    hostname: clickhouse1
    depends_on:
      - zookeeper
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config1.xml:/etc/clickhouse-server/config.xml
      - ./docker-entrypoint-initdb.d1:/docker-entrypoint-initdb.d
    ports:
      - 8123:8123
      - 9000:9000
      - 9004:9004

  clickhouse2:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse2
    hostname: clickhouse2
    depends_on:
      - zookeeper
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config2.xml:/etc/clickhouse-server/config.xml
      - ./docker-entrypoint-initdb.d2:/docker-entrypoint-initdb.d

  clickhouse3:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse3
    hostname: clickhouse3
    depends_on:
      - zookeeper
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./config3.xml:/etc/clickhouse-server/config.xml
      - ./docker-entrypoint-initdb.d3:/docker-entrypoint-initdb.d
  