version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3.5.9
    hostname: zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  clickhouse:
    image: yandex/clickhouse-server:21.7.8.58
    container_name: clickhouse
    hostname: clickhouse
    depends_on:
      - zookeeper
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
      nproc:
        soft: 131072
        hard: 131072
    volumes:
      - ./after-service-init-db.sh:/after-service-init-db.sh
      - ./conf/config.xml:/etc/clickhouse-server/config.xml
      - ./config.d:/etc/clickhouse-server/config.d
    ports:
      - 8123:8123
      - 9000:9000
      - 9004:9004
      - 9363:9363
  
  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    hostname: prometheus
    depends_on:
      - clickhouse
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090

  exporter:
    image: f1yegor/clickhouse-exporter:latest
    container_name: exporter
    hostname: exporter
    depends_on:
      - prometheus
    command:
      - -scrape_uri=http://clickhouse:8123/
    ports:
      - 9116:9116

  # grafana:
  #   image: grafana/grafana:latest
  #   container_name: grafana
  #   hostname: grafana
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3000:3000

  grafana:
    build:
      context: .
      dockerfile: Dockerfile-grafana
    image: grafana-clickhouse:1.0.0
    container_name: grafana
    hostname: grafana
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource 
    depends_on:
      - prometheus
    ports:
      - 3000:3000

  