apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  revisionHistoryLimit: 5 # 保留的“历史版本”个数。所以，如果把它设置为 0，你就再也不能做回滚操作了
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # 在一次“滚动”中，Deployment 控制器还可以创建多少个新 Pod
      maxUnavailable: 1 # 在一次“滚动”中，Deployment 控制器可以删除多少个旧 Pod
    rollingUpdate:
      maxSurge: 50% # 50% * DESIRED 数量
      maxUnavailable: 50%
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        version: v1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80